import React from "react";
import Head from "next/head";

import Image from "next/image";
import { useAuth } from "../context/AuthContext";
import PageTitle from "../components/PageTitle";
import ThirdsCard from "../components/ThirdsCard";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageTitle heading="Contact" message="Get in contact below"></PageTitle>
      <ThirdsCard
        headOne="One"
        textOne="one"
        headTwo="Two"
        textTwo="two"
        headThree="Three"
        textThree="three"
      ></ThirdsCard>
    </>
  );
}
